# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc5a7e459bdfbb959e11c306a8953599362d94fd6b0ab4abb632628b70d47a7029542f7c64e09abc60cc66610da9c6bb51cb313e10c4de221dff55083b8b56e5

test:
  secret_key_base: 298e7fe47d455bfd278f84eee9622c0932e7c3b39a41b5840548ff6de4614853bc8c7acdc0c59f4d2dbf1848ea9099104e440946459e91f5c407d44f3c9a9e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
